use strict;
use warnings;
#my $verilog_o = 'LUT_sincos_32.txt';
my $file = 'LUT_sincos_64.txt';
#my $top_name = 'LUT_CASE_32';
my $count = 0;
open my $info, $file or die "Could not open $file: $!";
#open(my $genverilog, '>', $filename) or die "Could not open file '$filename' $!";
#print $fh "module $top_name\n";
#print $fh "My first report generated by perl\n";
#print $fh "My first report generated by perl\n";

while( my $line = <$info>)  {
    chomp $line;
    print "4'b$count : begin\n";
    print "data_out =64'h$line;\n";
    print "end\n";
    last if ++$count == 16;
}


close $info;


