###################################################################

# Created by write_sdc on Wed Oct 12 18:12:55 2016

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 10 [current_design]
set_max_area 0
set_driving_cell -lib_cell TBUFX20TS [get_ports rst]
set_driving_cell -lib_cell TBUFX20TS [get_ports load_i]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[5]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[4]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[3]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[2]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[1]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Value_i[0]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[54]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[53]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[52]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[51]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[50]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[49]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[48]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[47]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[46]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[45]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[44]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[43]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[42]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[41]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[40]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[39]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[38]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[37]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[36]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[35]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[34]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[33]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[32]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[31]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[30]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[29]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[28]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[27]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[26]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[25]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[24]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[23]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[22]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[21]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[20]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[19]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[18]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[17]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[16]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[15]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[14]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[13]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[12]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[11]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[10]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[9]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[8]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[7]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[6]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[5]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[4]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[3]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[2]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[1]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {Shift_Data_i[0]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports Left_Right_i]
set_driving_cell -lib_cell TBUFX20TS [get_ports Bit_Shift_i]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_latency -source 0.5  [get_clocks clk]
set_clock_uncertainty -setup 0.5  [get_clocks clk]
set_clock_uncertainty -hold 0  [get_clocks clk]
set_clock_transition -max -rise 0.5 [get_clocks clk]
set_clock_transition -max -fall 0.5 [get_clocks clk]
set_clock_transition -min -rise 0.5 [get_clocks clk]
set_clock_transition -min -fall 0.5 [get_clocks clk]
set_input_delay -clock clk  -max 3  [get_ports rst]
set_input_delay -clock clk  -min 2  [get_ports rst]
set_input_delay -clock clk  -max 3  [get_ports load_i]
set_input_delay -clock clk  -min 2  [get_ports load_i]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[5]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[5]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[4]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[4]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[3]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[3]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[2]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[2]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[1]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[1]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Value_i[0]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Value_i[0]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[54]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[54]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[53]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[53]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[52]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[52]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[51]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[51]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[50]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[50]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[49]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[49]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[48]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[48]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[47]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[47]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[46]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[46]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[45]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[45]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[44]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[44]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[43]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[43]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[42]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[42]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[41]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[41]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[40]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[40]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[39]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[39]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[38]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[38]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[37]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[37]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[36]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[36]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[35]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[35]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[34]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[34]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[33]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[33]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[32]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[32]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[31]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[31]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[30]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[30]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[29]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[29]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[28]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[28]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[27]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[27]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[26]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[26]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[25]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[25]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[24]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[24]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[23]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[23]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[22]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[22]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[21]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[21]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[20]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[20]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[19]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[19]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[18]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[18]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[17]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[17]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[16]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[16]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[15]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[15]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[14]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[14]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[13]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[13]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[12]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[12]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[11]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[11]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[10]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[10]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[9]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[9]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[8]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[8]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[7]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[7]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[6]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[6]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[5]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[5]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[4]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[4]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[3]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[3]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[2]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[2]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[1]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[1]}]
set_input_delay -clock clk  -max 3  [get_ports {Shift_Data_i[0]}]
set_input_delay -clock clk  -min 2  [get_ports {Shift_Data_i[0]}]
set_input_delay -clock clk  -max 3  [get_ports Left_Right_i]
set_input_delay -clock clk  -min 2  [get_ports Left_Right_i]
set_input_delay -clock clk  -max 3  [get_ports Bit_Shift_i]
set_input_delay -clock clk  -min 2  [get_ports Bit_Shift_i]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[54]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[54]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[53]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[53]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[52]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[52]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[51]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[51]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[50]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[50]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[49]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[49]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[48]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[48]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[47]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[47]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[46]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[46]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[45]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[45]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[44]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[44]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[43]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[43]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[42]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[42]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[41]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[41]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[40]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[40]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[39]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[39]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[38]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[38]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[37]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[37]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[36]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[36]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[35]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[35]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[34]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[34]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[33]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[33]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[32]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[32]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[31]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[31]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[30]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[30]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[29]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[29]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[28]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[28]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[27]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[27]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[26]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[26]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[25]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[25]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[24]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[24]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[23]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[23]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[22]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[22]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[21]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[21]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[20]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[20]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[19]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[19]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[18]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[18]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[17]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[17]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[16]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[16]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[15]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[15]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[14]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[14]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[13]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[13]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[12]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[12]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[11]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[11]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[10]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[10]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[9]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[9]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[8]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[8]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[7]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[7]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[6]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[6]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[5]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[5]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[4]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[4]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[3]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[3]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[2]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[2]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[1]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[1]}]
set_output_delay -clock clk  -max 0  [get_ports {N_mant_o[0]}]
set_output_delay -clock clk  -min -3  [get_ports {N_mant_o[0]}]
