#!/bin/tcsh
#Script to build Oggonachip Hardware
#lazuara@csi.com

#Check parameters
if ( $#argv == 0 ) then
	echo "Usage: $0 <edif-file> [ampbe] [description TAG] [par opt1] [par arg1] [par opt2] [par arg2] [par opt3] [par arg3]"
	exit 1
else
	set TAG=$3
	if ( $#argv >= 3) then
		set TAG=-$3
	endif
	if ( $#argv >= 4) then
		set TAG=$TAG-par$4$5$6$7$8$9
	endif

	if ( $#argv >= 2 ) then
	switch ($argv[2])
		case [m]	 
			goto map
			breaksw
		case [p]
			goto par
			breaksw
		case [b]
			goto bit
			breaksw
		case [e]
			goto exo
			breaksw
		endsw 
	endif

	ngdbuild -a -p  XCV800HQ240-4 -uc xsv800_32b.ucf  $1.edf
map:
	map -u $1
par:
	par -w $4 $5 $6 $7 $8 $9 $1 $1$TAG
bit:
	bitgen -w $1$TAG B$1$TAG
exo:
	promgen -p exo -o $1$TAG.exo -x 1M -c 0xFF -w  -u 0 B$1$TAG.bit
endif





#rm -rf WORK
#rm dc_command.log
#rm -rf xsv800_32b.db
#rm -rf xsv800_32b.edif
#dc_shell -f build_xsv800_32b.dc &> dc_command.log










