###################################################################

# Created by write_sdc on Tue Oct 18 20:47:17 2016

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 10 [current_design]
set_max_area 0
set_driving_cell -lib_cell TBUFX20TS [get_ports rst]
set_driving_cell -lib_cell TBUFX20TS [get_ports load_b_i]
set_driving_cell -lib_cell TBUFX20TS [get_ports intAS]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[63]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[62]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[61]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[60]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[59]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[58]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[57]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[56]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[55]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[54]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[53]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[52]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[51]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[50]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[49]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[48]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[47]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[46]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[45]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[44]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[43]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[42]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[41]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[40]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[39]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[38]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[37]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[36]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[35]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[34]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[33]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[32]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[31]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[30]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[29]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[28]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[27]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[26]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[25]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[24]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[23]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[22]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[21]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[20]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[19]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[18]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[17]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[16]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[15]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[14]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[13]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[12]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[11]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[10]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[9]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[8]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[7]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[6]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[5]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[4]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[3]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[2]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[1]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDX[0]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[63]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[62]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[61]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[60]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[59]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[58]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[57]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[56]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[55]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[54]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[53]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[52]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[51]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[50]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[49]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[48]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[47]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[46]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[45]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[44]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[43]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[42]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[41]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[40]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[39]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[38]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[37]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[36]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[35]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[34]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[33]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[32]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[31]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[30]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[29]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[28]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[27]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[26]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[25]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[24]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[23]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[22]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[21]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[20]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[19]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[18]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[17]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[16]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[15]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[14]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[13]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[12]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[11]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[10]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[9]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[8]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[7]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[6]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[5]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[4]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[3]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[2]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[1]}]
set_driving_cell -lib_cell TBUFX20TS [get_ports {intDY[0]}]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_latency -source 0.5  [get_clocks clk]
set_clock_uncertainty -setup 0.5  [get_clocks clk]
set_clock_uncertainty -hold 0  [get_clocks clk]
set_clock_transition -max -rise 0.5 [get_clocks clk]
set_clock_transition -max -fall 0.5 [get_clocks clk]
set_clock_transition -min -rise 0.5 [get_clocks clk]
set_clock_transition -min -fall 0.5 [get_clocks clk]
set_input_delay -clock clk  -max 3.5  [get_ports rst]
set_input_delay -clock clk  -min 1  [get_ports rst]
set_input_delay -clock clk  -max 3.5  [get_ports load_b_i]
set_input_delay -clock clk  -min 1  [get_ports load_b_i]
set_input_delay -clock clk  -max 3.5  [get_ports intAS]
set_input_delay -clock clk  -min 1  [get_ports intAS]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[63]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[63]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[62]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[62]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[61]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[61]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[60]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[60]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[59]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[59]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[58]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[58]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[57]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[57]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[56]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[56]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[55]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[55]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[54]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[54]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[53]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[53]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[52]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[52]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[51]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[51]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[50]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[50]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[49]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[49]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[48]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[48]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[47]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[47]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[46]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[46]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[45]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[45]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[44]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[44]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[43]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[43]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[42]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[42]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[41]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[41]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[40]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[40]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[39]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[39]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[38]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[38]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[37]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[37]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[36]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[36]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[35]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[35]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[34]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[34]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[33]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[33]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[32]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[32]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[31]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[31]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[30]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[30]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[29]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[29]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[28]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[28]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[27]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[27]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[26]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[26]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[25]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[25]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[24]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[24]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[23]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[23]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[22]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[22]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[21]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[21]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[20]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[20]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[19]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[19]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[18]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[18]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[17]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[17]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[16]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[16]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[15]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[15]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[14]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[14]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[13]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[13]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[12]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[12]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[11]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[11]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[10]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[10]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[9]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[9]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[8]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[8]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[7]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[7]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[6]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[6]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[5]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[5]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[4]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[4]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[3]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[3]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[2]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[2]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[1]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[1]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDX[0]}]
set_input_delay -clock clk  -min 1  [get_ports {intDX[0]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[63]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[63]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[62]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[62]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[61]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[61]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[60]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[60]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[59]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[59]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[58]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[58]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[57]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[57]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[56]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[56]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[55]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[55]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[54]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[54]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[53]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[53]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[52]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[52]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[51]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[51]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[50]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[50]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[49]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[49]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[48]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[48]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[47]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[47]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[46]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[46]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[45]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[45]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[44]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[44]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[43]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[43]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[42]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[42]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[41]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[41]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[40]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[40]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[39]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[39]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[38]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[38]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[37]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[37]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[36]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[36]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[35]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[35]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[34]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[34]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[33]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[33]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[32]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[32]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[31]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[31]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[30]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[30]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[29]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[29]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[28]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[28]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[27]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[27]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[26]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[26]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[25]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[25]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[24]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[24]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[23]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[23]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[22]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[22]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[21]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[21]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[20]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[20]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[19]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[19]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[18]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[18]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[17]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[17]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[16]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[16]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[15]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[15]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[14]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[14]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[13]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[13]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[12]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[12]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[11]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[11]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[10]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[10]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[9]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[9]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[8]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[8]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[7]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[7]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[6]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[6]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[5]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[5]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[4]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[4]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[3]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[3]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[2]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[2]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[1]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[1]}]
set_input_delay -clock clk  -max 3.5  [get_ports {intDY[0]}]
set_input_delay -clock clk  -min 1  [get_ports {intDY[0]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[62]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[62]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[61]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[61]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[60]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[60]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[59]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[59]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[58]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[58]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[57]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[57]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[56]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[56]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[55]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[55]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[54]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[54]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[53]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[53]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[52]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[52]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[51]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[51]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[50]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[50]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[49]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[49]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[48]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[48]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[47]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[47]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[46]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[46]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[45]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[45]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[44]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[44]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[43]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[43]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[42]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[42]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[41]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[41]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[40]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[40]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[39]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[39]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[38]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[38]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[37]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[37]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[36]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[36]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[35]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[35]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[34]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[34]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[33]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[33]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[32]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[32]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[31]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[31]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[30]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[30]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[29]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[29]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[28]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[28]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[27]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[27]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[26]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[26]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[25]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[25]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[24]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[24]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[23]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[23]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[22]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[22]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[21]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[21]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[20]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[20]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[19]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[19]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[18]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[18]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[17]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[17]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[16]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[16]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[15]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[15]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[14]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[14]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[13]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[13]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[12]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[12]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[11]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[11]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[10]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[10]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[9]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[9]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[8]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[8]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[7]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[7]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[6]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[6]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[5]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[5]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[4]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[4]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[3]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[3]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[2]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[2]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[1]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[1]}]
set_output_delay -clock clk  -max 2  [get_ports {DMP_o[0]}]
set_output_delay -clock clk  -min 1  [get_ports {DMP_o[0]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[62]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[62]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[61]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[61]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[60]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[60]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[59]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[59]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[58]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[58]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[57]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[57]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[56]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[56]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[55]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[55]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[54]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[54]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[53]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[53]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[52]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[52]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[51]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[51]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[50]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[50]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[49]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[49]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[48]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[48]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[47]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[47]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[46]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[46]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[45]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[45]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[44]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[44]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[43]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[43]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[42]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[42]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[41]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[41]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[40]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[40]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[39]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[39]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[38]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[38]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[37]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[37]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[36]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[36]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[35]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[35]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[34]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[34]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[33]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[33]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[32]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[32]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[31]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[31]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[30]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[30]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[29]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[29]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[28]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[28]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[27]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[27]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[26]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[26]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[25]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[25]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[24]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[24]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[23]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[23]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[22]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[22]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[21]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[21]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[20]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[20]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[19]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[19]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[18]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[18]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[17]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[17]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[16]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[16]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[15]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[15]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[14]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[14]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[13]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[13]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[12]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[12]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[11]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[11]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[10]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[10]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[9]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[9]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[8]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[8]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[7]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[7]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[6]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[6]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[5]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[5]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[4]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[4]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[3]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[3]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[2]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[2]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[1]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[1]}]
set_output_delay -clock clk  -max 2  [get_ports {DmP_o[0]}]
set_output_delay -clock clk  -min 1  [get_ports {DmP_o[0]}]
set_output_delay -clock clk  -max 2  [get_ports zero_flag_o]
set_output_delay -clock clk  -min 1  [get_ports zero_flag_o]
set_output_delay -clock clk  -max 2  [get_ports real_op_o]
set_output_delay -clock clk  -min 1  [get_ports real_op_o]
set_output_delay -clock clk  -max 2  [get_ports sign_final_result_o]
set_output_delay -clock clk  -min 1  [get_ports sign_final_result_o]
