vlib leon/work
vcom  leon/amba.vhd 
vcom  leon/target.vhd 
vcom  leon/device.vhd 
vcom  leon/config.vhd 
vcom  leon/sparcv8.vhd 
vcom  leon/iface.vhd
vcom  leon/macro.vhd
vcom  leon/debug.vhd 
vcom  leon/ambacomp.vhd 
vcom  leon/multlib.vhd
vcom  leon/tech_generic.vhd 
vcom  leon/tech_atc35.vhd 
vcom  leon/tech_atc25.vhd 
vcom  leon/tech_umc18.vhd
vcom  leon/tech_fs90.vhd 
vcom  leon/bprom.vhd 
vcom  leon/tech_virtex.vhd 
vcom  leon/tech_map.vhd
vcom  leon/fpulib.vhd 
vcom  leon/meiko.vhd 
#vcom  leon/fpu_lth.vhd 
#vcom  leon/fpu_core.vhd 
vcom  leon/fp1eu.vhd 
vcom  leon/mul.vhd
vcom  leon/div.vhd 
vcom  leon/clkgen.vhd 
vcom  leon/rstgen.vhd 
vcom  leon/iu.vhd 
vcom  leon/icache.vhd 
vcom  leon/dcache.vhd
vcom  leon/cachemem.vhd 
vcom  leon/acache.vhd 
vcom  leon/cache.vhd 
vcom  leon/proc.vhd 
vcom  leon/irqctrl2.vhd
vcom  leon/apbmst.vhd 
vcom  leon/ahbarb.vhd 
vcom  leon/lconf.vhd 
vcom  leon/wprot.vhd 
vcom  leon/ahbtest.vhd 
vcom  leon/ahbstat.vhd
vcom  leon/timers.vhd 
vcom  leon/irqctrl.vhd 
vcom  leon/uart.vhd 
vcom  leon/ioport.vhd 
vcom  leon/mctrl.vhd
#vcom  leon/ahbmst.vhd 
#vcom  leon/dcom_uartvcom  leon/dcom.vhd 
#vcom  leon/dma.vhd 
#vcom  leon/dsu.vhd 
#vcom  leon/dsu_mem.vhd
#vcom  leon/pci_arb.vhd 
#vcom  leon/pci_is.vhd 
#vcom  leon/pci.vhd 
vcom  leon/mcore.vhd
vcom  leon/leon_pci.vhd 
vcom  leon/leon.vhd

vcom  tbench/leonlib.vhd 
vcom  tbench/iram.vhd 
vcom  tbench/testmod.vhd 
vcom  tbench/mspram.vhd 
vcom  tbench/bprom.vhd
vcom  tbench/tbgen.vhd 
vcom  tbench/tblib.vhd 
vcom  tbench/tbdef.vhd 
vcom  tbench/tbleon.vhd 
vcom  tbench/tb_msp.vhd



