
source ASIC_fpmult_arch3_syn.tcl
source ASIC_fpmult_arch3_syn_clkgating.tcl
source ASIC_fpu_operators_syn.tcl
source ASIC_fpu_operators_syn_1GHZ.tcl
source ASIC_fpu_operators_syn_clkgating.tcl
source ASIC_fpu_arch3_syn.tcl
source ASIC_fpu_arch3_syn_1GHZ.tcl
source ASIC_fpu_arch3_syn_clkgating.tcl
source ASIC_fpu_arch2_syn.tcl
source ASIC_fpu_arch2_syn_1GHZ.tcl
source ASIC_fpu_arch2_syn_clkgating.tcl
