#!/bin/sh -h 
dir_name=`dirname $0`
if [ "${dir_name}" = "." ]; then
    cd $dir_name
    dir_name=`pwd`
fi
if [ -d $dir_name/../../../../../../../../../../../../../.. ]; then
    cd $dir_name/../../../../../../../../../../../../../..
fi
if [ -f /home/local/ESTUDIANTES/jsequeira/Documents/Dise-o-ASIC-FPGA-FPU/ASIC_FLOW/ASIC_cordic_Arch2/integracion_fisica/simulacion_logica_sintesis/SINGLE/simv.daidir/debug_dump/fsearch/.create_fsearch_db ]; then
    if [ ! -f /home/local/ESTUDIANTES/jsequeira/Documents/Dise-o-ASIC-FPGA-FPU/ASIC_FLOW/ASIC_cordic_Arch2/integracion_fisica/simulacion_logica_sintesis/SINGLE/simv.daidir/debug_dump/fsearch/fsearch.db ]; then
        /home/local/ESTUDIANTES/jsequeira/Documents/Dise-o-ASIC-FPGA-FPU/ASIC_FLOW/ASIC_cordic_Arch2/integracion_fisica/simulacion_logica_sintesis/SINGLE/simv.daidir/debug_dump/fsearch/.create_fsearch_db
    fi
fi
