#vcom leon/iface-ooac.vhd
#vcom leon/ambacomp.vhd
#vcom leon/debug.vhd
vcom leon/ddmlib.vhd
vcom leon/ddm16.vhd
vcom leon/mdctlib.vhd
vcom leon/mdctcomp.vhd
vcom leon/mdct_syn.vhd
#vcom leon/mcoremdct.vhd
vcom leon/mcore-ooac.vhd
vcom leon/leon_sim32.vhd
#vcom leon/leon-ooac.vhd
