#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned long RP;
typedef unsigned long RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef unsigned long long TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I673;
    unsigned long long I674;
    unsigned  I675[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I682;
    E_fn  I683;
    struct iptmpl * I684;
    unsigned I686;
    struct eblk * I687;
} eblk_struct;
typedef struct {
    RP  I682;
    RP  I683;
    RP  I684;
    unsigned I686;
    RP  I687;
} RmaEblk;
typedef union {
    double I673;
    unsigned long long I674;
    unsigned  I675[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I723;
    RmaEblk  I681;
    U  I724;
    US  I725 :1;
    US  I726 :4;
    US  I176 :2;
    US  state :2;
    US  I728 :1;
    US  I729 :2;
    US  I730 :2;
    US  fHsim :1;
    US  I731 :1;
    scalar  newval;
    scalar  I733;
    RP  I734;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I713;
    scalar  I714;
    scalar  I715;
    scalar  I716;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I718;
    EBLK  I719;
    void * I720;
    UP   I721[1];
};
struct RmaMPSched {
    RP  I713;
    scalar  I714;
    scalar  I715;
    scalar  I716;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I718;
    RmaEblk  I719;
    RP  I720;
    RP   I721[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I713;
    scalar  I714;
    scalar  I715;
    scalar  I716;
    scalar  I176;
    U  I718;
    RmaEblk  I719;
    scalar  I730;
    scalar  I738;
    scalar  I739;
    scalar  I740;
    U  I741;
    RmaClockStruct  I742;
    RmaClockStruct  I743;
    U  state;
    U  I744;
    RP  I684;
    RP  I745;
    RP  I746;
    RP   I721[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I748;
    void * I749;
};
typedef struct {
    RmaEblk  I681;
    RP  I750;
    scalar  I751;
    scalar  I730;
    scalar  I752;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I713;
    scalar  I714;
    scalar  I715;
    scalar  I716;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I718;
    RmaEblk  I719;
    scalar  I730;
    scalar  I738;
    scalar  I739;
    scalar  I740;
    U  state :4;
    U  I754 :28;
    RmaClockStruct  I742;
    RmaClockStruct  I743;
    RP  I755;
    RP  I684;
    RP  I756;
    RP   I721[1];
};
typedef struct red_t {
    U  I757;
    U  I758;
    U  I635;
} RED;
typedef struct predd {
    PD_e  I176;
    RED   I759[0];
} PREDD;
union rhs_value {
    vec32  I760;
    scalar  I751;
    vec32  * I730;
    double I761;
    U  I762;
};
typedef struct nbs_t {
    struct nbs_t * I763;
    struct nbs_t * I765;
    void (* I766)(struct nbs_t * I767);
    unsigned I768 :1;
    unsigned I769 :1;
    unsigned I770 :1;
    unsigned I771 :1;
    unsigned I772 :27;
    U  I773;
    void * I774;
    union rhs_value I775;
    vec32  I673;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I777;
} NBS;
typedef struct {
    RP  I778;
    RP  I745;
    RP  I684;
    RP  I746;
    RmaEblk  I681;
    RmaEblk  I779;
    RP  I780;
    scalar  I751;
    scalar  I730;
    char state;
    uscope_t  I781;
    U  I782;
    RP  I783;
    scalar  I738;
    scalar  I739;
    scalar  I740;
    RmaClockStruct  I742;
    RmaClockStruct  I743;
    RP  I720;
} RmaPulse;
typedef struct {
    UP  I784;
    int * I785;
} TypeData;
struct etype {
    U  I552 :8;
    U  I553 :24;
    U  I554;
    U  I555 :1;
    U  I556 :1;
    U  I557 :1;
    U  I558 :1;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :1;
    U  I564 :4;
    U  I565 :1;
    U  I566 :1;
    U  I567 :1;
    U  I568 :1;
    U  I569 :1;
    U  I570 :1;
    U  I571 :1;
    U  I572 :1;
    U  I573 :2;
    U  I574 :1;
    U  I575 :2;
    U  I576 :1;
    U  I577 :1;
    U  I578 :4;
    U  I579;
    TypeData  * I580;
    U  I581;
    U  I582;
    U  I583 :1;
    U  I584 :1;
    U  I585 :1;
    U  I586 :1;
    U  I587 :2;
    U  I588 :2;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :1;
    U  I593 :1;
    U  I594 :1;
    U  I595 :1;
    U  I596 :1;
    U  I597 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I789 :1;
    U  I790 :1;
    U  I791 :1;
    U  I792 :1;
    U  I793 :1;
    U  I794 :1;
    U  I795 :1;
    U  I796 :1;
    U  I797 :1;
    U  I798 :1;
    U  I799 :1;
    U  I800 :1;
    U  I801 :1;
    U  I802 :1;
    U  I803 :1;
    U  I804 :1;
    U  I805 :1;
    U  I806 :1;
    QIRDModuleType  I807 :2;
    U  I808 :1;
    U  I809 :1;
    U  I810 :1;
    U  I811 :1;
    U  I812 :1;
    U  I813 :1;
    U  I814 :1;
    U  I815 :1;
    U  I816 :1;
    U  I817 :1;
    U  I818 :1;
    U  I819 :1;
    U  I820 :1;
    U  I821 :1;
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  * I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    U  I115;
    struct qrefer * I116;
    U  * I118;
    unsigned * I119;
    void * I120;
    U  I121;
    U  I122;
    struct classStaticReferData * I123;
    U  I125;
    U  I126;
    U  I127;
    U  * I128;
    U  I129;
    U  * I130;
    U  I131;
    U  I132;
    U  I133;
    U  * I134;
    U  I135;
    U  * I136;
    U  I137;
    U  I138;
    U  * I139;
    U  I140;
    U  I141;
    U  * I142;
    U  * I143;
    U  * I144;
    U  I145;
    U  I146;
    U  I147;
    U  I148;
    U  I149;
    struct qrefee * I150;
    U  * I152;
    U  I153;
    struct qdefrefee * I154;
    U  * I156;
    int (* I157)(void);
    char * I158;
    U  I159;
    U  I160;
    void * I161;
    void * I162;
    NumLibs_t  I163;
    char * I164;
    U  * I165;
    U  I166;
    U  I167;
    U  I168;
    U  I169;
    U  I170;
    U  * I171;
    U  * I172;
    int I173;
    struct clock_load * I174;
    int I189;
    struct clock_data * I190;
    int I206;
    struct clock_hiconn * I207;
    U  I211;
    int I212;
    U  I213;
    int I214;
    U  * I215;
    U  * I216;
    U  I217;
    void * I218;
    U  I219;
    U  I220;
    UP  * I221;
    void * I222;
    U  I223;
    UP  * I224;
    U  * I225;
    int (* I226)(void);
    U  * I227;
    UP  * I228;
    U  * I229;
    U  I230 :1;
    U  I231 :31;
    U  I232;
    U  I233;
    UP  * I234;
    U  * I235;
    U  I236 :1;
    U  I237 :1;
    U  I238 :1;
    U  I239 :1;
    U  I240 :28;
    U  I241;
    U  I242;
    U  I243;
    U  I244 :31;
    U  I245 :1;
    UP  * I246;
    UP  * I247;
    U  * I248;
    U  * I249;
    U  * I250;
    UP  * I251;
    UP  * I252;
    UP  * I253;
    U  * I254;
    UP  * I255;
    UP  * I256;
    UP  * I257;
    char * I258;
    U  I259;
    U  I260;
    U  I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    UP  * I266;
    UP  * I267;
    UP  * I268;
    UP  * I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    U  I275;
    U  I276;
    U  I277;
    U  I278;
    U  I279;
    U  I280;
    U  I281;
    U  I282;
    char * I283;
    U  * I284;
    U  I285;
    U  I286;
    U  I287;
    UP  * I288;
    UP  * I289;
    UP  * I290;
    UP  * I291;
    struct daidirInfo * I292;
    struct vcs_tftable * I294;
    U  I296;
    UP  * I297;
    UP  * I298;
    U  I299;
    U  I300;
    U  I301;
    UP  * I302;
    U  * I303;
    struct qird_hil_data * I304;
    UP  (* I306)(void);
    UP  (* I307)(void);
    UP  (* I308)(void);
    UP  (* I309)(void);
    UP  (* I310)(void);
    int * I311;
    int (* I312)(void);
    char * I313;
    UP  * I314;
    UP  * I315;
    UP  (* I316)(void);
    int (* I317)(void);
    int * I318;
    int (* I319)(void);
    int * I320;
    char * I321;
    U  * I322;
    U  * I323;
    U  * I324;
    U  * I325;
    void * I326;
    U  I327;
    void * I328;
    U  I329;
    U  I330;
    U  I331;
    U  I332;
    U  I333;
    U  I334;
    UP  * I335;
    U  * I336;
    U  * I337;
    U  I338 :15;
    U  I339 :14;
    U  I340 :1;
    U  I341 :1;
    U  I342 :1;
    U  I343 :3;
    U  I344 :1;
    U  I345 :1;
    U  I346 :17;
    U  I347 :3;
    U  I348 :5;
    U  I349 :2;
    U  I350 :1;
    U  I351 :31;
    struct scope * I352;
    U  I354;
    U  I355;
    U  I356;
    U  * I357;
    U  * I358;
    U  * I359;
    U  I360;
    U  I361;
    U  I362;
    struct pcbt * I363;
    U  I373;
    U  I374;
    U  I375;
    U  I376;
    void * I377;
    void * I378;
    void * I379;
    int I380;
    U  * I381;
    U  I382;
    U  I383;
    U  I384;
    U  I385;
    U  I386;
    U  I387;
    U  I388;
    void * I389;
    UP  * I390;
    U  I391;
    U  I392;
    void * I393;
    U  I394;
    void * I395;
    U  I396;
    void * I397;
    U  I398;
    int (* I399)(void);
    int (* I400)(void);
    void * I401;
    void * I402;
    void * I403;
    U  I404;
    U  I405;
    U  I406;
    U  I407;
    U  I408;
    U  I409;
    char * I410;
    U  I411;
    U  * I412;
    U  I413;
    U  * I414;
    U  I415;
    U  I416;
    U  I417;
    U  I418;
    U  I419;
    U  I420;
    U  * I421;
    U  I422;
    U  I423;
    U  * I424;
    U  I425;
    U  I426;
    U  * I427;
    char * I428;
    U  I429;
    U  I430;
    U  I431;
    U  I432;
    U  * I433;
    U  * I434;
    U  I435;
    U  * I436;
    U  * I437;
    U  I438;
    U  I439;
    U  I440;
    U  I441;
    struct cosim_info * I442;
    U  I444;
    U  * I445;
    U  I446;
    U  I447;
    U  * I448;
    U  I449;
    U  * I450;
    U  I451;
    U  I452;
    U  * I453;
    U  I454;
    U  * I455;
    U  I456;
    U  * I457;
    U  I458;
    U  I459;
    U  I460;
    U  I461;
    U  I462;
    U  I463;
    U  I464;
    U  I465;
    U  I466;
    U  * I467;
    U  * I468;
    void (* I469)(void);
    U  * I470;
    UP  * I471;
    struct mhdl_outInfo * I472;
    UP  * I474;
    U  I475;
    UP  * I476;
    U  I477;
    void * I478;
    U  * I479;
    void * I480;
    char * I481;
    int (* I482)(void);
    U  * I483;
    char * I484;
    char * I485;
    U  I486;
    U  * I487;
    char * I488;
    U  I489;
    struct regInitInfo * I490;
    UP  * I492;
    U  * I493;
    char * I494;
    U  I495;
    U  I496;
    U  I497;
    U  I498;
    U  I499;
    U  I500;
    U  I501;
    U  I502;
    U  * I503;
    U  * I504;
    U  I505;
    U  I506;
    U  I507;
    U  I508;
    UP  * I509;
    U  I510;
    UP  * I511;
    U  I512;
    U  I513;
    U  I514;
    U  * I515;
    U  I516;
    U  I517;
    U  I518;
    U  * I519;
    U  * I520;
    UP  * I521;
    UP  * I522;
    void * I523;
    UP  I524;
    void * I525;
    void * I526;
    void * I527;
    void * I528;
    void * I529;
    UP  I530;
    U  * I531;
    U  * I532;
    void * I533;
    U  I534 :1;
    U  I535 :31;
    U  I536;
    U  I537;
    U  I538;
    int I539;
    void * I540;
    UP  * I541;
    U  * I542;
    U  I543;
    char * I544;
    U  * I545;
    U  * I546;
    char * I547;
    int * I548;
    UP  * I549;
    struct etype * I550;
    U  I598;
    U  I599;
    U  I600;
    U  * I601;
    void * I602;
    U  I603;
    U  I604;
    void * I605;
    U  I606;
    U  I607;
    U  * I608;
    U  I609;
    U  * I610;
    U  I611;
    U  I612;
    U  * I613;
};
typedef struct pcbt {
    U  * I365;
    UP  I366;
    U  I367;
    U  I368;
    U  I369;
    U  I370;
    U  I371;
    U  I372;
} PCBT;
struct iptmpl {
    QIRD  * I688;
    struct vcs_globals_t * I689;
    void * I691;
    UP  I692;
    UP  I693;
    struct iptmpl * I684[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I866[256];
    struct _hsimPeriodL * I829;
} HsimPeriodL;
typedef struct {
    U   I868[2];
    U  I869 :1;
    U  I870 :1;
    U  I871 :8;
    U  I872 :8;
    U  I873 :8;
    U  I874 :4;
    unsigned long long I875;
    unsigned long long I876;
    unsigned long long I877;
    unsigned long long I878;
    unsigned long long I879;
    U  I880;
    U  I881;
    U  I882;
    U  I883;
    HsimPeriodL  * I884;
    HsimPeriodL  * I885;
    U  I886;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I887;
    InstNum  I888;
    U  I837;
    scalar  I889;
    UB  I890;
    UB  I891;
    UB  I892;
    U  I893;
    U  I894;
    U  I895;
    U  I896;
    U  I897;
    HsimSignalMonitor  * I898;
    RmaTimeStamp64  I899;
    U  I900;
    RmaTimeStamp64  I901;
} HsimNodeRecord;
typedef struct {
    RP  I902;
    RP  I684;
} RmaIbfIp;
typedef struct {
    RP  I902;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I681;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I681;
    RP  I903;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I681;
    RP  I904;
    RP  I903;
    vec32  I905;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I681;
    RP  I904;
    RP  I903;
    vec32   I729[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I681;
    RP  I904;
    RP  I903;
    scalar   I906[1];
} RmaAnySchedECg;
typedef struct {
    RP  I907;
} RmaRootCbkCg;
typedef struct {
    RP  I908;
} RmaRootVcdCg;
typedef struct {
    RP  I909;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I681;
    RP  I910;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I677 :30;
    U  I911 :1;
    U  I912 :1;
    vec32  I760;
    U  I913;
    RP  I914;
    RP  I915;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I921;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I618;
    RmaIbfPcode   I921[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I921;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I922;
    U  I923 :3;
    U  I924 :1;
    U  I925 :1;
    U  I926 :16;
} RmaNbaGateOfn;
typedef struct {
    NBS  I927;
    RmaIbfPcode  I922;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I930;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I930;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I931;
    U  * I932;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I933;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I933;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I681;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I681;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I681;
    RP  pcode;
    RP  pfn;
    scalar  I934;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I935;
    RP  I936;
    RP  I937;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I681;
    RP  pcode;
    U  I837;
    U   I670[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I759;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I759;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1070;
        RP  I1318;
        RP  I1328;
    } I734;
    RmaIbfPcode  I922;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I938;
    RmaIbfPcode  I922;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I922;
    RmaMps  I939;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I940;
    RmaIbfPcode  I922;
    RmaEblk  I719;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I922;
    RmaMpspNewCsdf  I941;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I941;
    RmaIbfPcode  I922;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I635;
    RmaTransEventHdr  I843;
    RP  I756;
    RmaIbfPcode  I922;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I635;
    RmaTransEventHdr  I843;
    RP  I756;
    RmaIbfPcode  I922;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I635;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I942;
    U  I943;
    RmaTransEventHdr  I843;
    RP  I756;
    RmaIbfPcode  I922;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I942;
    U  I943;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I944;
    RmaTransEventHdr  I843;
    RP  I756;
    RmaIbfPcode  I922;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I944;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I759;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1318;
        RP  I1328;
    } I734;
    RmaIbfPcode  I922;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I759;
    RmaEblk  I681;
    RmaIbfPcode  I922;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I829;
    struct TableAssign_ * I750;
    U  I5;
    U  iinput;
    RP  ptable;
    RP  I933;
} TableAssign;
typedef struct {
    U  I5;
    RP  I750;
    RP  I946;
} RmaTableAssignList;
typedef struct {
    RP  I947;
} RmaWakeupListCg;
typedef struct {
    U  I948;
    U  I949;
    RmaTimeStamp   I950[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I951;
} RmaConditionsMdb;
typedef struct {
    RP  I829;
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I829;
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I962;
} RmaTcCoreConditional;
typedef struct {
    RP  I829;
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I962;
    RP  I963;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I829;
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I963;
    RP  I964;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I967;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I962;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I962;
    RP  I963;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I963;
    RP  I964;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I963;
    RP  I964;
    RP  I967;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    RP  I962;
    RP  I967;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I952;
    RP  I676;
    U  I953;
    scalar  I926;
    scalar  I954;
    US  I955 :1;
    US  I956 :1;
    US  I957 :1;
    US  I958 :1;
    US  I959 :1;
    US  I960 :1;
    US  I961 :5;
    U  I968;
    RP  I969;
    RP  I970;
    RP  I962;
    RP  I971;
    RP  I972;
    RmaTimeStamp  I973;
} RmaTcCoreNochange;
typedef struct {
    RP  I974;
    RP  I829;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I951;
    RmaTimeStamp  I975;
    scalar  I976;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I829;
    RP  I951;
    RmaTimeStamp  I975;
    scalar  I976;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I975;
    scalar  I976;
    US  I926;
    RP  I963;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I829;
    RmaTimeStamp  I975;
    scalar  I976;
    US  I926;
    RP  I963;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I963;
    RP  I977;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I967;
    RP  I963;
    RP  I977;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I829;
    RP  I963;
    RP  I977;
    U  I965;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I978;
    U  I979;
    FlatNodeNum  I980;
    U  I837;
    U  I981;
    U  I982;
    RmaIbfPcode  I922;
    union {
        scalar  I983;
        vec32  I984;
        scalar  * I985;
        vec32  * I986;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I829;
    RP  I750;
    RP  I987;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I988;
    U  I989 :1;
    U  I990 :1;
    U  I991 :1;
    U  I992 :4;
    U  I578 :25;
    U  I993;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1357;
        RmaSwitchGateInCbkListInfo  I2;
    } I649;
    RmaIbfPcode  I922;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I994;
    scalar  val;
    scalar  I176 :4;
    scalar  I995 :1;
    scalar  I996 :1;
    scalar  I997 :1;
    scalar  I998 :1;
    RP  I763;
    RP  I999;
    RP  I980;
    RP  I1000;
    RP  I1001;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1002;
    UB  I1003;
    RmaNonEdgeLoadData1  * I1004;
    RmaNonEdgeLoadData1  * I750;
} RmaNonEdgeLoadHdr1;
typedef struct RmaChildClockProp_ {
    RP  I763;
    RP  I1005;
    RP  I980;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I1004;
    RmaChildClockProp  * I750;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I1006;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I176 :5;
    U  I177 :12;
    U  I178 :1;
    U  I179 :2;
    U  I180 :1;
    U  I181 :1;
    U  I182 :1;
    U  I183 :9;
    U  I184;
    U  I185;
    void (* pfn)(void * I187, char val);
};
typedef struct clock_data {
    U  I192 :1;
    U  I193 :1;
    U  I194 :1;
    U  I195 :1;
    U  I176 :5;
    U  I177 :12;
    U  I196 :6;
    U  I197 :1;
    U  I179 :2;
    U  I180 :1;
    U  I183 :1;
    U  I198;
    U  I199;
    U  I200;
    U  I184;
    U  I201;
    U  I202;
    U  I203;
    U  I204;
    U  I205;
} HdbsClockData;
struct clock_hiconn {
    U  I209;
    U  I210;
    U  I184;
    U  I179;
};
typedef struct _RmaDaiCg {
    RP  I1007;
    RP  I1008;
    U  I1009;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I1007;
    RP  I1010;
    RP  I1011;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1012;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I711;
    U   I712[32];
};
struct futq_slot1 {
    U  I708;
    struct futq_slot2  I709[32];
};
struct futq_info {
    U  I704;
    U  I705;
    struct futq_slot1  I706[32];
};
struct futq {
    struct futq * I694;
    struct futq * I696;
    RmaEblk  * I697;
    RmaEblk  * I698;
    U  I686;
};
struct sched_table {
    struct futq * I699;
    struct futq I700;
    struct hash_bucket * I701;
    struct hash_bucket * I703;
};
struct dummyq_struct {
    clock_struct  I1016;
    EBLK  * I1017;
    EBLK  * I1018;
    struct futq * I1019;
    struct futq * I1020;
    struct futq * I1021;
    struct sched_table * I1022;
    struct futq_info * I1024;
    U  I1026;
    U  I1027;
    U  I1028;
    struct millenium * I1029;
    EBLK  * I1031;
    EBLK  * I1032;
    EBLK  * I1033;
    EBLK  * I1034;
    EBLK  * I1035;
    EBLK  * I1036;
    EBLK  * I1037;
    EBLK  * I1038;
    EBLK  * I1039;
    EBLK  * I1040;
    EBLK  * I1041;
    EBLK  * I1042;
    EBLK  * I1043;
    EBLK  * I1044;
    EBLK  * I1045;
    EBLK  * I1046;
    EBLK  * I1047;
    EBLK  * I1048;
    MPS  * I1049;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I682;
    EBLK  * I1050;
    int I1051;
    struct _lqueue * I723;
} Queue;
typedef struct {
    EBLK  I1053;
    U  I1054;
    union {
        void * pHeap;
        Queue  * pList;
    } I649;
    Queue   I1055[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_0_0 (UB  * pcode, scalar  val);
void  hsM_0_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_0_2 (UB  * pcode);
void  hsM_1_0 (UB  * pcode, scalar  val);
void  hsM_1_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_1_2 (UB  * pcode);
void  hsM_2_0 (UB  * pcode, scalar  val);
void  hsM_2_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_2_2 (UB  * pcode);
void  hsM_3_0 (UB  * pcode, scalar  val);
void  hsM_3_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_3_2 (UB  * pcode);
void  hsM_4_0 (UB  * pcode, scalar  val);
void  hsM_4_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_4_2 (UB  * pcode);
void  hsM_7_0 (UB  * pcode, scalar  val);
void  hsM_10_0 (UB  * pcode, scalar  val);
void  hsM_11_0 (UB  * pcode, scalar  val);
void  hsM_26_0 (UB  * pcode, scalar  val);
void  hsM_26_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_26_2 (UB  * pcode);
void  hsM_27_0 (UB  * pcode, scalar  val);
void  hsM_27_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_27_2 (UB  * pcode);
void  hsM_28_0 (UB  * pcode, scalar  val);
void  hsM_28_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_28_2 (UB  * pcode);
void  hsM_29_0 (UB  * pcode, scalar  val);
void  hsM_29_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_29_2 (UB  * pcode);
void  hsM_29_9 (UB  * pcode, scalar  val);
void  hsM_30_0 (UB  * pcode, scalar  val);
void  hsM_30_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_30_2 (UB  * pcode);
void  hsM_31_0 (UB  * pcode, scalar  val);
void  hsM_31_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_31_2 (UB  * pcode);
void  hsM_32_0 (UB  * pcode, scalar  val);
void  hsM_32_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_32_2 (UB  * pcode);
void  hsM_32_9 (UB  * pcode, scalar  val);
void  hsM_33_0 (UB  * pcode, scalar  val);
void  hsM_33_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_33_2 (UB  * pcode);
void  hsM_34_0 (UB  * pcode, scalar  val);
void  hsM_34_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_34_2 (UB  * pcode);
void  hsM_35_0 (UB  * pcode, scalar  val);
void  hsM_35_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_35_2 (UB  * pcode);
void  hsM_36_0 (UB  * pcode, scalar  val);
void  hsM_36_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_36_2 (UB  * pcode);
void  hsM_37_0 (UB  * pcode, scalar  val);
void  hsM_37_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_37_2 (UB  * pcode);
void  hsM_38_0 (UB  * pcode, scalar  val);
void  hsM_38_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_38_2 (UB  * pcode);
void  hsM_39_0 (UB  * pcode, scalar  val);
void  hsM_39_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_39_2 (UB  * pcode);
void  hsM_40_0 (UB  * pcode, scalar  val);
void  hsM_40_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_40_2 (UB  * pcode);
void  hsM_41_0 (UB  * pcode, scalar  val);
void  hsM_41_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_41_2 (UB  * pcode);
void  hsM_42_0 (UB  * pcode, scalar  val);
void  hsM_42_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_42_2 (UB  * pcode);
void  hsM_43_0 (UB  * pcode, scalar  val);
void  hsM_43_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_43_2 (UB  * pcode);
void  hsM_44_0 (UB  * pcode, scalar  val);
void  hsM_44_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_44_2 (UB  * pcode);
void  hsM_45_0 (UB  * pcode, scalar  val);
void  hsM_45_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_45_2 (UB  * pcode);
void  hsM_46_0 (UB  * pcode, scalar  val);
void  hsM_46_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_46_2 (UB  * pcode);
void  hsM_47_0 (UB  * pcode, scalar  val);
void  hsM_47_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_47_2 (UB  * pcode);
void  hsM_48_0 (UB  * pcode, scalar  val);
void  hsM_48_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_48_2 (UB  * pcode);
void  hsM_49_0 (UB  * pcode, scalar  val);
void  hsM_49_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_49_2 (UB  * pcode);
void  hsM_50_0 (UB  * pcode, scalar  val);
void  hsM_50_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_50_2 (UB  * pcode);
void  hsM_51_0 (UB  * pcode, scalar  val);
void  hsM_51_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_51_2 (UB  * pcode);
void  hsM_52_0 (UB  * pcode, scalar  val);
void  hsM_52_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_52_2 (UB  * pcode);
void  hsM_53_0 (UB  * pcode, scalar  val);
void  hsM_53_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_53_2 (UB  * pcode);
void  hsM_54_0 (UB  * pcode, scalar  val);
void  hsM_54_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_54_2 (UB  * pcode);
void  hsM_55_0 (UB  * pcode, scalar  val);
void  hsM_55_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_55_2 (UB  * pcode);
void  hsM_56_0 (UB  * pcode, scalar  val);
void  hsM_56_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_56_2 (UB  * pcode);
void  hsM_56_9 (UB  * pcode, scalar  val);
void  hsM_57_0 (UB  * pcode, scalar  val);
void  hsM_57_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_57_2 (UB  * pcode);
void  hsM_58_0 (UB  * pcode, scalar  val);
void  hsM_58_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_58_2 (UB  * pcode);
void  hsM_58_5 (UB  * pcode, UB  val);
void  hsM_59_0 (UB  * pcode, scalar  val);
void  hsM_59_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_59_2 (UB  * pcode);
void  hsM_59_5 (UB  * pcode, UB  val);
void  hsM_60_0 (UB  * pcode, scalar  val);
void  hsM_60_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_60_2 (UB  * pcode);
void  hsM_61_0 (UB  * pcode, scalar  val);
void  hsM_61_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_61_2 (UB  * pcode);
void  hsM_62_0 (UB  * pcode, scalar  val);
void  hsM_62_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_62_2 (UB  * pcode);
void  hsM_63_0 (UB  * pcode, scalar  val);
void  hsM_63_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_63_2 (UB  * pcode);
void  hsM_64_0 (UB  * pcode, scalar  val);
void  hsM_64_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_64_2 (UB  * pcode);
void  hsM_64_9 (UB  * pcode, scalar  val);
void  hsM_65_0 (UB  * pcode, scalar  val);
void  hsM_65_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_65_2 (UB  * pcode);
void  hsM_66_0 (UB  * pcode, scalar  val);
void  hsM_66_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_66_2 (UB  * pcode);
void  hsM_67_0 (UB  * pcode, scalar  val);
void  hsM_67_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_67_2 (UB  * pcode);
void  hsM_68_0 (UB  * pcode, scalar  val);
void  hsM_69_0 (UB  * pcode, scalar  val);
void  hsM_70_0 (UB  * pcode, scalar  val);
void  hsM_70_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_70_2 (UB  * pcode);
void  hsM_71_0 (UB  * pcode, scalar  val);
void  hsM_72_0 (UB  * pcode, scalar  val);
void  hsM_73_0 (UB  * pcode, scalar  val);
void  hsM_74_0 (UB  * pcode, scalar  val);
void  hsM_75_0 (UB  * pcode, scalar  val);
void  hsM_76_0 (UB  * pcode, scalar  val);
void  hsM_77_0 (UB  * pcode, scalar  val);
void  hsM_77_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_77_2 (UB  * pcode);
void  hsM_78_0 (UB  * pcode, scalar  val);
void  hsM_78_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_78_2 (UB  * pcode);
void  hsM_79_0 (UB  * pcode, scalar  val);
void  hsM_79_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_79_2 (UB  * pcode);
void  hsM_80_0 (UB  * pcode, scalar  val);
void  hsM_80_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_80_2 (UB  * pcode);
void  hsM_81_0 (UB  * pcode, scalar  val);
void  hsM_81_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_81_2 (UB  * pcode);
void  hsM_82_0 (UB  * pcode, scalar  val);
void  hsM_82_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_82_2 (UB  * pcode);
void  hsM_83_0 (UB  * pcode, scalar  val);
void  hsM_83_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_83_2 (UB  * pcode);
void  hsM_84_0 (UB  * pcode, scalar  val);
void  hsM_84_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_84_2 (UB  * pcode);
void  hsM_85_0 (UB  * pcode, scalar  val);
void  hsM_85_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_85_2 (UB  * pcode);
void  hsM_86_0 (UB  * pcode, scalar  val);
void  hsM_86_1 (UB  * pcode, scalar  val, U  I627, scalar  * I1074);
void  hsM_86_2 (UB  * pcode);
void  hsG_0 (struct dummyq_struct * I1062, EBLK  * I1063, U  I635);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

